#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Workaround for: https://github.com/sorin-ionescu/prezto/issues/1744
#
export HISTFILE="${ZDOTDIR:-$HOME}/.zhistory" # The path to the history file.

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# zsh-notify must be configured *after* loading the module
#

# Set a custom notification title for success.
zstyle ':notify:*' success-title 'Success'

# Set a custom notification title for failure.
zstyle ':notify:*' error-title 'Failure'

# Customize to your needs...

# Source additional aliases.
if [[ -s "${ZDOTDIR:-$HOME}/.zalias" ]]; then
  source "${ZDOTDIR:-$HOME}/.zalias"
fi
